name: docker

on:
  push:
    branches: main
    tags: ["*"]

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake build-essential cmake curl file libtool
      - name: Cross build multi-arch binary
        run: |
          mkdir dist
          for arch in amd64; do
            env BUILD_TARGET=$arch ./scripts/cross-build.sh
            [ "$arch" = "armv7" ] && arch="arm" 
            mkdir -p dist/$arch && cp build/ttyd dist/$arch/ttyd
          done
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Determine docker tags
        id: docker_tag
        run: |
          case $GITHUB_REF in
            refs/tags/*)
              TAG_NAME=${GITHUB_REF#refs/tags/}
              echo "DOCKER_TAG=rohja/ttyd:${TAG_NAME}" >> $GITHUB_ENV
              ;;
            *)
              echo "DOCKER_TAG=rohja/ttyd:latest" >> $GITHUB_ENV
          esac
      - name: build/push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ env.DOCKER_TAG }}
